/**
 * Hook types barrel export.
 *
 * Re-exports all hook-related types from a single entry point.
 */

// Event types and type guards
export {
	type PermissionMode,
	type PermissionSuggestion,
	type PermissionSuggestionDestination,
	type NotificationType,
	type SessionEndReason,
	type ConfigChangeSource,
	type InstructionsMemoryType,
	type InstructionsLoadReason,
	type StopFailureErrorType,
	type ElicitationAction,
	type ElicitationFormField,
	type PreToolUseEvent,
	type PermissionRequestEvent,
	type PermissionDeniedEvent,
	type PostToolUseEvent,
	type PostToolUseFailureEvent,
	type NotificationEvent,
	type StopEvent,
	type StopFailureEvent,
	type SubagentStartEvent,
	type SubagentStopEvent,
	type UserPromptSubmitEvent,
	type PreCompactEvent,
	type PostCompactEvent,
	type SetupEvent,
	type SessionStartEvent,
	type SessionEndEvent,
	type TeammateIdleEvent,
	type TaskCreatedEvent,
	type TaskCompletedEvent,
	type ConfigChangeEvent,
	type InstructionsLoadedEvent,
	type CwdChangedEvent,
	type FileChangedEvent,
	type WorktreeCreateEvent,
	type WorktreeRemoveEvent,
	type ElicitationEvent,
	type ElicitationResultEvent,
	type ClaudeHookEvent,
	type HookEventName,
	isPreToolUseEvent,
	isPermissionRequestEvent,
	isPermissionDeniedEvent,
	isPostToolUseEvent,
	isPostToolUseFailureEvent,
	isNotificationEvent,
	isSubagentStartEvent,
	isSubagentStopEvent,
	isSessionStartEvent,
	isSessionEndEvent,
	isStopFailureEvent,
	isPostCompactEvent,
	isElicitationEvent,
	isElicitationResultEvent,
	isToolEvent,
} from './events';

// Protocol envelope types
export {
	type HookEventEnvelope,
	type HookResultEnvelope,
	isValidHookEventEnvelope,
	generateId,
} from './envelope';

// Result types and helpers
export {
	type HookAction,
	type HookResultPayload,
	type HookOutput,
	type UniversalOutputFields,
	type PreToolUseOutput,
	type PreToolUsePermissionDecision,
	type PostToolUseOutput,
	type PostToolUseFailureOutput,
	type PermissionRequestOutput,
	type PermissionRequestDecisionBehavior,
	type PermissionDeniedOutput,
	type UserPromptSubmitOutput,
	type SessionStartOutput,
	type StopOutput,
	type SubagentStopOutput,
	type NotificationOutput,
	type SubagentStartOutput,
	type PreCompactOutput,
	type PostCompactOutput,
	type ConfigChangeOutput,
	type CwdChangedOutput,
	type FileChangedOutput,
	type WorktreeCreateOutput,
	type TaskCreatedOutput,
	type TaskCompletedOutput,
	type TeammateIdleOutput,
	type ElicitationOutput,
	type ElicitationResultOutput,
	createPreToolUseAllowResult,
	createPreToolUseDenyResult,
	createPreToolUseAskResult,
	createAskUserQuestionResult,
	createPermissionRequestAllowResult,
	createPermissionRequestDenyResult,
	createElicitationResult,
	createWorktreeCreateResult,
	createStopBlockResult,
} from './result';
